server:
  port: 9090
  servlet:
    context-path: /demo


#热部署生效
#设置重启的目录
#classpath目录下的WEB-INF文件夹内容修改不重启
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
