server:
  port: 9090
  servlet:
    context-path: /demo

#热部署生效
#设置重启的目录
#classpath目录下的WEB-INF文件夹内容修改不重启
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  profiles:
    active: dev

# redis 配置
  redis:
      #地址
      host: 127.0.0.1
      #端口号
      port: 6379
      #密码
      password:
      #默认数据库
      database: 1
      lettuce:
        #连接池配置
        pool:
          #最大连接数
          max-active: 32
          #等待时间
          max-wait: 300ms
          #最大空闲
          max-idle: 16
          #最小空闲
          min-idle: 8
      timeout: 100ms